CREATE TABLE USER_TABLE (
  USER_ID INTEGER NOT NULL PRIMARY KEY,
  USER_NAME VARCHAR(255) NOT NULL,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL
);

/*
DELETE FROM USER_TABLE;

DROP TABLE USER_TABLE;
*/

SELECT *
FROM USER_TABLE
where user_id = 4
;

update USER_TABLE
set user_name = 'KAT', FIRST_NAME = 'TIMBER', LAST_NAME = 'WOLVES'
where user_id = 43;

update USER_TABLE
set user_name = 'WALL', FIRST_NAME = 'WASHINGTON', LAST_NAME = 'WIZARDS'
where user_id = 43;